### ISSUE TITLE
"DBT is not installed" - issue that may come up for users who installed dbt using homebrew or in a non-standard location

### ISSUE THREAD

**Issue by epugmire** [AltimateAI/vscode-dbt-power-user#87]
Hi,

For some reason, my VS Code bar is saying "dbt is not installed" in my terminal due to the dbt power user extension:

![image](https://user-images.githubusercontent.com/8509218/138988972-27b8bbab-6697-4dda-aeea-cb414ba65363.png)

But as you can see it is installed:
![image](https://user-images.githubusercontent.com/8509218/138989041-b4f12397-e9a9-46fc-8e21-50c32f661500.png)

When I try installing (clicking yes in the first screenshot), I am left with this error as it tries to install dbt:
![image](https://user-images.githubusercontent.com/8509218/138989091-843401fb-9980-48a4-b516-4bfebfec5b59.png)

Any thoughts? If I cannot fix this, I will just end up using Terminal and VSCode in tandem (not ideal). 

Thank you!

**Comment by sijain2** [comment]
Thanks. Ran into this problem and homebrew was the culprit. I thought the purpose of using homebrew was so that it won't install dependencies already present on the system. Is that not so?

**Comment by dustinwilson** [comment]
I ran into this problem today, too, after trying the extension. Thanks for providing this workaround, but unless I'm mistaken this problem will reoccur every time dbt is updated. I'm using dbt-snowflake, but substitute below with your `$HOMEBREW_PREFIX` (usually `/opt/homebrew/` or `/usr/local/`) and dbt package. This is the example from my system:

```
/opt/homebrew/Cellar/dbt-snowflake/1.2.0/libexec/bin/python
```

If you notice there's a `1.2.0` version in the path, so if dbt comes out with dbt 1.2.1 and I update the path changes. The way homebrew works is that everything is installed into the Cellar by package name and then version, and the preferred version (usually the newest, but you can override that on a per package basis) is linked outside the Cellar to be used. So, instead of using the path provided by `dbt debug` you should instead use the linked version which in my case would be:

```
/opt/homebrew/opt/dbt-snowflake/libexec/bin/python
```

Also, I thought I'd point out to people looking here for a solution that the interpreter path can be changed by opening the command palette (<kbd>⌘</kbd> + <kbd>⇧</kbd> + <kbd>P</kbd>) and searching for `Python: Select Interpreter`. I'm not usually a Python developer and therefore have no experience using it in VSCode, so I had no idea where that was.

@sijain2: That usually is the case, but dbt's homebrew formulae link to specific versions they want to use.

**Comment by JoshuaSmart-Olufemi** [comment]
I have a similar issue. I am using windows and installed my dbt with pip install dbt-postgres. I connected my venv to VS Code bit the sign still persists

**Comment by Nevermetyou65** [comment]
I still have this problem on ubuntu. 
I can not get rid of it. 
Uninstalling does not help me at all. Can someone help me pls?

**Comment by talarczykco** [comment]
Make sure the version of the VS Code extension is recent enough to match the version of dbt. I recently encountered a cloud development environment that was using an old version of `code-server` that limited my marketplace extensions; no error was given from the marketplace, just old versions of the extension. Once I updated code-server, I was able to install a recent enough extension that it fixed this problem.

**Comment by matthiasr** [comment]
I had success with selecting the interpreter _at the workspace level_. I have multiple repositories in the workspace, and there's a venv specifically for my DBT project, so I really don't want to do that, but it makes it so Power User can find dbt at least.

**Comment by apd-bbaker** [comment]
Still struggling with this and my devs in 2024, but generally the fix is to:

1.  Create a fresh venv using `python3 -m venv ~/.venv`.
2. Once that exists, activate the new venv with `source ~/.venv/activate`.
3. Install dbt flavor of your choice with `pip install dbt-snowflake`.
4. Switch the Python interpreter - at the workspace level if you're using multiple repos at once - by hitting Cmd+Shift+P and searching `Python Interpreter`. Set it to the correct path of `~/.venv/bin/python3.12`
5. The final and most important. Uninstall the dbt Power User extension, hit restart extensions, then install dbt Power User again. No matter what you do, it will not detect that the correct package is installed until it's been removed and reinstalled.

**Comment by mdesmet** [comment]
> The final and most important. Uninstall the dbt Power User extension, hit restart extensions, then install dbt Power User again. No matter what you do, it will not detect that the correct package is installed until it's been removed and reinstalled.

That seems incorrect. Reinstalling the extension doesn't yield any effect. Restarting/reloading vscode should be enough as we cannot detect changes to the environment (dbt being installed through CLI commands).

**Comment by augustoschnorr** [comment]
Hey there!

I am also facing this issue as of April 2025. I have tried the steps @apd-bbaker posted but I am still not able to make it work on my Mac.

Have anyone else found a solution for this?

**Comment by sambeetm** [comment]
Same issue here. Tried all the possible solutions and nothing has worked yet. I am using a Mac with virtual env for dbt.
